"""P4-26: writes the footstep SuperCollider sources (assets/audio/src/sfx_step_<surface>_NN.scd), doc 08 s11.2.
Run: uv run --no-project python tools/audio/gen_steps.py --render
(writes the sources, renders them, then re-renders the louder variants of each surface with a lower --peak so
every variant's RMS sits within SPREAD_DB of the quietest; P4-26 QA. Without --render it only writes sources.)
CEO session 2026-10-09: the P1-10 steps (a sine "boop" body under noise) sounded bad. These are noise only:
a heel strike, a toe roll 60 to 120 ms later, a scuff between them and the surface texture (soil grains,
leaf brush, plank knock). Each variant draws its own numbers from its seed, so variants differ in timing,
weight and texture, not only in pitch. Every sound is a placeholder."""
import array
import math
import subprocess
import sys
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "assets" / "audio" / "src"
SPREAD_DB = 1.5  # max RMS spread between the variants of one surface (QA asked for about 2 dB)
N = 6  # variants per surface; soundscape.gd never plays the same one twice in a row

# Shared pieces (SuperCollider). @SEED@ is the variant seed. The language-side rrand calls run once at
# load time, so a variant renders the same every time.
HEAD = """// @ID@ (placeholder, P4-26). One footstep on @SURF@, mono, 3D, @DUR@ s. Generated by tools/audio/gen_steps.py,
// doc 08 section 11.2. @DESC@
(
var toe, heel, tone, roll, grit, gd, extra;
thisThread.randSeed = @SEED@;
toe = rrand(0.06, 0.12); heel = rrand(0.75, 1.0); tone = rrand(0.85, 1.18); roll = rrand(0.35, 0.65);
grit = rrand(0.6, 1.0); gd = rrand(1400, 2600); extra = rrand(0.7, 1.0);
(
	channels: 1,
	duration: @DUR@,
	defs: [
"""

# Heel and toe: low-passed noise thuds (no oscillator), a scuff in between. Used by dirt and corn.
FOOT = """			var hEnv = EnvGen.ar(Env.perc(0.002, 0.07, curve: -6));
			var wEnv = EnvGen.ar(Env.perc(0.004, 0.11, curve: -5));
			var tEnv = EnvGen.ar(Env([0, 0, 1, 0], [toe, 0.003, 0.06], [0, 0, -6]));
			var sEnv = EnvGen.ar(Env([0, 0, 1, 0], [toe * 0.4, toe * 0.5, 0.05], [0, 2, -4]));
			var thud = LPF.ar(LPF.ar(WhiteNoise.ar, 320 * tone), 320 * tone) * hEnv * heel * 2.5;
			var weight = LPF.ar(BrownNoise.ar, 140 * tone) * wEnv * heel * 1.6;
			var toeHit = LPF.ar(BPF.ar(WhiteNoise.ar, 650 * tone, 1.4), 1800) * tEnv * roll * 1.2;
			var scuff = BPF.ar(PinkNoise.ar, 1300 * tone, 1.2) * sEnv * 0.35;
			var cEnv = EnvGen.ar(Env([0, 1, 0.35, 0.9, 0], [0.004, toe, 0.004, 0.11], -4));
			var grains = Decay2.ar(Dust.ar(gd), 0.0002, 0.0025) * WhiteNoise.ar;
			var crunch = LPF.ar(BPF.ar(grains, 2200 * tone, 1.6), 4500) * cEnv * grit * @CRUNCH@;
"""

T = {}
T["dirt"] = (HEAD + """		SynthDef(\\step, { |out = 0|
""" + FOOT + """			Out.ar(out, HPF.ar(HPF.ar(thud + weight + toeHit + scuff + crunch, 30), 30));
		})
	],
	events: [[0, [\\s_new, \\step, -1, 0, 0]]]
)
)
""").replace("@CRUNCH@", "0.9")

T["corn"] = (HEAD + """		SynthDef(\\step, { |out = 0|
""" + FOOT + """			var lEnv = EnvGen.ar(Env([0, 1, 0.6, 0], [0.025, toe + 0.05, 0.22 * extra], [2, -1, -4]));
			var leaf = BPF.ar(WhiteNoise.ar, LFNoise1.kr(9).range(2600, 5200) * tone, 0.9) * LFNoise2.ar(90).range(0, 1).squared;
			var dry = HPF.ar(Decay2.ar(Dust.ar(450 * extra), 0.0002, 0.002) * WhiteNoise.ar, 2800);
			Out.ar(out, HPF.ar(HPF.ar(thud + weight + toeHit + scuff + crunch + (LPF.ar(leaf * 0.9 + (dry * 0.6), 7000) * lEnv * extra), 30), 30));
		})
	],
	events: [[0, [\\s_new, \\step, -1, 0, 0]]]
)
)
""").replace("@CRUNCH@", "0.5")

# Wood: a short noise burst excites damped plank resonances (heel, then toe), straw grit on top, and a
# faint stick-slip creak on even variants. Ring times stay under 0.12 s so it knocks, never rings.
T["wood"] = HEAD + """		SynthDef(\\step, { |out = 0, creak = 0|
			var f = 120 * tone;
			var hEx = LPF.ar(WhiteNoise.ar, 1400) * EnvGen.ar(Env.perc(0.0008, 0.014, curve: -4)) * heel;
			var tEx = LPF.ar(WhiteNoise.ar, 1800) * EnvGen.ar(Env([0, 0, 1, 0], [toe, 0.001, 0.012], [0, 0, -4])) * roll;
			var plank = Klank.ar(`[[f, f * rrand(2.2, 2.5), 340 * tone, 690 * tone, 1350 * tone], [1, 0.55, 0.45, 0.25, 0.12],
				[0.11, 0.07, 0.05, 0.035, 0.02]], hEx + tEx) * 0.22;
			var thud = LPF.ar(LPF.ar(WhiteNoise.ar, 260 * tone), 260 * tone) * EnvGen.ar(Env.perc(0.002, 0.05, curve: -6)) * heel * 1.5;
			var cEnv = EnvGen.ar(Env([0, 1, 0.3, 0.7, 0], [0.003, toe, 0.004, 0.08], -4));
			var grains = Decay2.ar(Dust.ar(gd * 0.6), 0.0002, 0.0025) * WhiteNoise.ar;
			var straw = LPF.ar(BPF.ar(grains, 3000, 1.5), 6000) * cEnv * grit * 0.4;
			var crEnv = EnvGen.ar(Env([0, 0, 1, 0.6, 0], [0.04, 0.04, 0.12, 0.08], [0, 2, 0, -3]));
			var stick = Decay2.ar(Impulse.ar(LFNoise1.kr(25).range(55, 110)), 0.0002, 0.002);
			var cr = Klank.ar(`[[520, 1130, 1870] * tone, [1, 0.5, 0.3], [0.02, 0.015, 0.01]], stick) * crEnv * creak * 0.015;
			Out.ar(out, HPF.ar(HPF.ar(plank + thud + straw + cr, 30), 30));
		})
	],
	events: [[0, [\\s_new, \\step, -1, 0, 0, \\creak, @CREAK@]]]
)
)
"""

DESC = {
    "dirt": "Heel and toe noise thuds, a scuff and dry soil grains (filtered Dust); no oscillator.",
    "corn": "The dirt step on softer soil plus a leaf brush (jittered BPF noise 2.6 to 5.2 kHz) and dry-leaf crackle.",
    "wood": "Barn planks: noise-excited damped Klank (heel, toe), a low thud, straw grit; a faint creak on even variants.",
}
DUR = {"dirt": 0.35, "corn": 0.5, "wood": 0.4}
SEED0 = {"dirt": 2610, "corn": 2620, "wood": 2630}

def render(ids: list[str], peak: float) -> None:
    subprocess.run(["uv", "run", "tools/audio/render.py", *ids, "--spectrogram", "--peak", str(peak)], cwd=ROOT, check=True)


def rms_db(sid: str) -> float:
    with wave.open(str(ROOT / "assets" / "audio" / f"{sid}.wav")) as w:
        a = array.array("h", w.readframes(w.getnframes()))
    return 20 * math.log10(math.sqrt(sum(x * x for x in a) / len(a)) / 32768)


V = [(f"sfx_step_{s}_{n:02d}", s, n) for s in ("dirt", "corn", "wood") for n in range(1, N + 1)]

if __name__ == "__main__":
    for sid, s, n in V:
        txt = T[s]
        for k, v in {"ID": sid, "SURF": s, "DUR": DUR[s], "DESC": DESC[s], "SEED": SEED0[s] + n,
                     "CREAK": 0 if n % 2 else 1}.items():
            txt = txt.replace(f"@{k}@", str(v))
        (OUT / f"{sid}.scd").write_bytes(txt.encode())
    print(" ".join(sid for sid, _, _ in V))
    if "--render" in sys.argv:
        render([sid for sid, _, _ in V], -1.0)
        for s in ("dirt", "corn", "wood"):
            ids = [sid for sid, s2, _ in V if s2 == s]
            peaks = dict.fromkeys(ids, -1.0)
            for _ in range(4):  # noise renders differ a little each time (README), so re-check after re-rendering
                levels = {sid: rms_db(sid) for sid in ids}
                top = min(levels.values()) + SPREAD_DB  # sub-30 Hz is filtered out, so whole-file RMS is the audible level
                over = [sid for sid, lv in levels.items() if lv > top + 0.2]
                for sid in over:
                    peaks[sid] = round(peaks[sid] - (levels[sid] - top), 2)
                    render([sid], peaks[sid])
                if not over:
                    break
            print(s, " ".join(f"{sid[-2:]}:{rms_db(sid):.1f}" for sid in ids))
