extends Node
## Doc 08 section 10: the one place that turns replicated state into sound. Autoload `Soundscape`.
## Runs on every peer, never talks to the network, only listens: `Creature.state_changed` (group
## `creature`, fires on host and clients), `Net.apply_received` lure, `Clock.phase_changed`.
##
## Two ambience layers (doc 08 section 4): wind and the night insect bed (no frogs, no day insects).
## Rule (doc 08 section 4.4): only `set_creature_state()` lowers the `bed` or `wind` layers, through
## `_tell_target`; the phase crossfade is equal-power between two beds, never through silence.
## P3-05 adds `hush()`, the scare build-up, as the one other path (doc 08 section 4.4 rule 1, Q-059).
## P3-08: the Taint heartbeat for the local Tainted player (polled from `Game.players`, Q-060).
## Every sound is a placeholder generated by `assets/audio/src/<id>.scd` (D-015).

const CATALOG := {  # id -> variants, bus, unit_size, max_distance, volume_db (doc 08 sections 3.2, 11)
	# P4-26 footsteps, 6 variants per surface (doc 08 section 11.2); dB re-matched by RMS (placeholder).
	&"sfx_step_dirt": {"n": 6, "bus": &"SFX", "unit": 3.0, "max": 40.0, "db": -8.0},
	&"sfx_step_corn": {"n": 6, "bus": &"SFX", "unit": 3.0, "max": 40.0, "db": -8.0},
	&"sfx_step_wood": {"n": 6, "bus": &"SFX", "unit": 3.0, "max": 40.0, "db": -8.0},
	&"sfx_beartrap_snap": {"n": 0, "bus": &"SFX", "unit": 6.0, "max": 110.0, "db": -4.0},
	&"sfx_pit_fall": {"n": 0, "bus": &"SFX", "unit": 6.0, "max": 110.0, "db": -4.0},
	&"sfx_whistle": {"n": 0, "bus": &"SFX", "unit": 20.0, "max": 220.0, "db": -4.0},
	&"vox_stranger_over_here": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_help": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_anyone": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_come": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_lost": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_hello": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"cre_door_bang": {"n": 1, "bus": &"Creature", "unit": 8.0, "max": 90.0, "db": -4.0},
	&"sfx_lantern_blow_out": {"n": 0, "bus": &"SFX", "unit": 4.0, "max": 40.0, "db": -6.0},
	&"mus_sting_chase": {"n": 0, "bus": &"Music", "db": -6.0},
	# P3-05 scares (doc 08 section 5.4), played by `scares.gd`; files from P3-08.
	# CEO listen 1 (2026-10-08): scare sounds redone; db re-matched to the old files' RMS (volume was "good").
	&"cre_jumpscare_hit": {"n": 0, "bus": &"Creature", "db": -8.0},
	# P4-17 per-body jumpscare (creature_body without "body_"); same level as the fallback above.
	&"cre_jumpscare_hit_gaunt": {"n": 0, "bus": &"Creature", "db": -8.0},
	&"cre_jumpscare_hit_scarecrow": {"n": 0, "bus": &"Creature", "db": -8.0},
	&"cre_jumpscare_hit_boar": {"n": 0, "bus": &"Creature", "db": -8.0},
	&"cre_jumpscare_hit_husk": {"n": 0, "bus": &"Creature", "db": -8.0},
	&"cre_lunge": {"n": 0, "bus": &"Creature", "db": -4.0},
	&"cre_presence_swell": {"n": 0, "bus": &"Creature", "db": -8.0},
	&"cre_corn_part": {"n": 2, "bus": &"Creature", "unit": 4.0, "max": 40.0, "db": -12.0},
	&"sfx_ragdoll_thud": {"n": 2, "bus": &"SFX", "unit": 4.0, "max": 40.0, "db": -4.0},
	&"sfx_door_slam": {"n": 0, "bus": &"SFX", "unit": 8.0, "max": 90.0, "db": -2.0},
	&"sfx_crow_burst": {"n": 0, "bus": &"SFX", "unit": 8.0, "max": 90.0, "db": 0.4},  # CEO: listen 1 +0.83 dB, listen 3 x1.4 amplitude (+2.9 dB)
	# P3-11 emote scream (doc 08 section 11.6), file from P3-08.
	# unit/max are inference: a 60 m Noise, like the tripwire bells row in section 3.2.
	&"vox_emote_scream": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 110.0, "db": -1.0},
	# P3-08. Ranges are inference (doc 08 section 3.2 has no row for them): a caw like the door bang,
	# cloth like a footstep. All placeholder levels.
	&"sfx_crow_caw": {"n": 3, "bus": &"SFX", "unit": 8.0, "max": 90.0, "db": -5.0},  # P3-09 possessed crow
	&"sfx_emote_cloth": {"n": 0, "bus": &"SFX", "unit": 3.0, "max": 30.0, "db": -10.0},  # P3-11 wave, point, shrug
	&"ui_paper_slide": {"n": 0, "bus": &"UI", "db": -10.4},  # P3-12 Dawn Report card: CEO listen 1 -2.5 dB, listen 2 a further -3.1 dB (30 percent amplitude)
	# P4-17 (doc 08 sections 6, 11). Callers belong to P4-06, P4-08, P4-14, P4-15 and the Creature owner. All placeholder
	# levels, trimmed by measured RMS toward the doc 08 section 2.4 targets; unit/max are inference (like the rows above).
	# Lurk signature variants: Creature plays `play_3d(&"cre_<body>_sig", pos)` (doc 08 section 6, n = 3 per body).
	&"cre_gaunt_sig": {"n": 3, "bus": &"Creature", "unit": 4.0, "max": 40.0, "db": 0.0},  # quiet file (-35 dB RMS), so no cut
	&"cre_scarecrow_sig": {"n": 3, "bus": &"Creature", "unit": 4.0, "max": 40.0, "db": -6.0},
	&"cre_boar_sig": {"n": 3, "bus": &"Creature", "unit": 5.0, "max": 50.0, "db": -9.0},
	&"cre_husk_sig": {"n": 3, "bus": &"Creature", "unit": 4.0, "max": 40.0, "db": -9.0},
	&"sfx_cart_squeak_loop": {"n": 0, "bus": &"SFX", "unit": 5.0, "max": 60.0, "db": -14.0},  # loop; pitch_scale follows pushers
	&"cre_gnaw": {"n": 0, "bus": &"Creature", "unit": 3.0, "max": 30.0, "db": -8.0},
	&"sfx_flare_shot": {"n": 0, "bus": &"SFX", "unit": 20.0, "max": 220.0, "db": -4.0},  # the loudest noise on the farm
	&"sfx_flare_hiss_loop": {"n": 0, "bus": &"SFX", "unit": 6.0, "max": 70.0, "db": -12.0},  # loop
	&"cre_flare_hit": {"n": 0, "bus": &"Creature", "unit": 8.0, "max": 90.0, "db": -6.0},
	&"vox_radio_squelch_on": {"n": 0, "bus": &"Voice", "db": -10.0},
	&"vox_radio_squelch_off": {"n": 0, "bus": &"Voice", "db": -10.0},
	&"vox_radio_low_battery": {"n": 0, "bus": &"Voice", "db": -18.0},
	&"vox_radio_dead": {"n": 0, "bus": &"Voice", "db": -10.0},
	&"vox_radio_static_loop": {"n": 0, "bus": &"Voice", "db": -22.0},  # loop; level follows creature proximity
	&"sfx_animal_chicken": {"n": 3, "bus": &"SFX", "unit": 4.0, "max": 45.0, "db": -8.0},
	&"sfx_animal_pig": {"n": 2, "bus": &"SFX", "unit": 4.0, "max": 45.0, "db": -8.0},
	&"sfx_animal_cow": {"n": 2, "bus": &"SFX", "unit": 5.0, "max": 55.0, "db": -8.0},
	&"sfx_animal_panic_01": {"n": 0, "bus": &"SFX", "unit": 5.0, "max": 60.0, "db": -6.0},  # chicken
	&"sfx_animal_panic_02": {"n": 0, "bus": &"SFX", "unit": 5.0, "max": 60.0, "db": -6.0},  # pig
	&"sfx_animal_panic_03": {"n": 0, "bus": &"SFX", "unit": 5.0, "max": 60.0, "db": -6.0},  # cow
	&"ui_click": {"n": 0, "bus": &"UI", "db": -8.0},
	&"ui_confirm": {"n": 0, "bus": &"UI", "db": -14.0},
	&"ui_deny": {"n": 0, "bus": &"UI", "db": -16.0},
	&"ui_coins": {"n": 0, "bus": &"UI", "db": -4.0},
	&"ui_stamp": {"n": 0, "bus": &"UI", "db": -10.0},
	&"ui_award_reveal": {"n": 0, "bus": &"UI", "db": -8.0},
	&"ui_shop_bell": {"n": 0, "bus": &"UI", "db": -4.0},
}
## Taint heartbeat (doc 08 sections 2.4, 8): "faint", local to the Tainted player only. Placeholder level.
const TAINT_DB := -20.0  # CEO listens: -42 barely audible, then double (+6 dB) at listens 2 and 3
## Doc 08 section 8: the Taint beat ducks 8 dB under the still heartbeat; the chase heartbeat reuses that loop (inference).
const TAINT_DUCK_DB := 8.0
## Ids not written to the `audio_play` log (one per stride would flood it).
const QUIET_LOG: Array[StringName] = [&"sfx_step_dirt", &"sfx_step_corn", &"sfx_step_wood"]
## Scare build-up (doc 03 section 13 "insects cut", "silence"), through `hush()`. Placeholder depth.
const HUSH_WIND_DB := 12.0
## Chase signature loops, one per body (doc 08 sections 5.3, 6): positional on the creature, loud (placeholder).
const SIG_UNIT := 8.0
const SIG_MAX := 90.0
const SIG_DB := -6.0
## Kill-warning heartbeat (OPEN_ISSUES playtest 8, P2-08 trial): local, rises over the chase. Placeholder numbers.
const CHASE_HEARTBEAT := true
const HEART_DB := [-34.0, -22.0]  ## doc 08 section 8 "Still" range
const HEART_PITCH := [1.0, 1.5]
const HEART_RAMP_S := 8.0
const BARN_DB := -34.0  ## barn lobby bed (the file is normalised loud: a brown-noise room tone); placeholder
const BARN_FADE_S := 2.0
const STRANGER_LINES: Array[StringName] = [&"vox_stranger_over_here", &"vox_stranger_help",
		&"vox_stranger_anyone", &"vox_stranger_come", &"vox_stranger_lost", &"vox_stranger_hello"]
## Layer levels in dB: [day, night] (doc 08 section 4.1, placeholder). No day insect bed: day is wind only.
const LAYERS := {
	&"wind": {"file": "amb_wind_loop", "day": -29.1, "night": -23.1, "pitch": 0.5},  # CEO listen 3: half frequency, -30 percent (-3.1 dB)
	&"insect_night": {"file": "amb_insect_bed_night", "day": -80.0, "night": -28.0},
	&"barn": {"file": "amb_barn_lobby_loop", "day": BARN_DB, "night": BARN_DB},  # gain by _barn, not the phase
}
const WIND_DROP_DB := 18.0  ## doc 08 section 4.3 stalk
const BED_OFF_DB := 60.0
const PHASE_FADE_S := 45.0  ## doc 08 section 4.1 dusk crossfade
const MAX_EMITTERS := 32  ## doc 08 section 2.3 rule 7
const STRIDE_M := 1.6  ## same stride as the host's footstep Noise (players.gd)
## P4-26: each step varies (CEO: footsteps sounded bad, repetitive). Placeholder ranges, tuned by ear.
const STEP_PITCH := Vector2(0.9, 1.1)
const STEP_DB := Vector2(-2.5, 1.0)
const CORN_MASK := 16  ## layer 5 corn, the same point query as players.gd `_step_kind`
const SILENT_DB := -80.0

var creature_state: StringName = &"lurk"
var creature_body: StringName = &""
var recent: Array[StringName] = []  ## last 8 sound ids (doc 08 section 10.4)

var _players: Dictionary = {}  ## layer -> AudioStreamPlayer
var _night := 0.0  ## 0 day bed, 1 night bed; equal-power crossfade
var _night_target := 0.0
var _barn := 0.0  ## 1 while in the lobby or recording (the barn bed)
var _report: DawnReport  ## the Dawn Report card, found when it is shown (set_report_open)
var _report_on := false
var _sig: AudioStreamPlayer3D  ## chase signature, a child of the creature node
var _heart: AudioStreamPlayer
var _taint: AudioStreamPlayer  ## the Taint heartbeat, alive only while the local player is Tainted
var _chase_t := 0.0
var _tell_db := {&"bed": 0.0, &"wind": 0.0}  ## offset below base, set only through _tell_target
var _tell_target := {&"bed": 0.0, &"wind": 0.0}
var _tell_rate := {&"bed": 60.0, &"wind": 9.0}  ## dB per second
var _dropped_t := 0.0
var _log_t := 0.0
var _emitters := 0
var _cache: Dictionary = {}
var _prev_pos: Dictionary = {}
var _stride: Dictionary = {}
var _rng := RandomNumberGenerator.new()
var _last_variant: Dictionary = {}  ## id -> last variant played, never repeated back to back
var _floors: Array[Rect2] = []  ## building footprints (wood floor), from the `doors` markers' buildings
var _floors_scene: Node  ## the scene `_floors` was built from


func _ready() -> void:
	_rng.randomize()
	for id in LAYERS:
		var p := AudioStreamPlayer.new()
		p.bus = &"Ambience"
		p.volume_db = SILENT_DB
		p.stream = _stream(String(LAYERS[id].file), true)
		p.pitch_scale = LAYERS[id].get("pitch", 1.0)
		add_child(p)
		_players[id] = p
	set_phase(Clock.phase, true)
	Clock.phase_changed.connect(set_phase)
	Net.apply_received.connect(_on_apply)
	Log.logged.connect(_on_logged)
	get_tree().node_added.connect(_on_node_added)
	for c in get_tree().get_nodes_in_group(&"creature"):
		_hook_creature(c)
	_apply_gains()
	_start_layers()


## Free players and drop cached streams so no AudioStreamWAV / playback outlives the tree ("resources still in use at exit").
func _exit_tree() -> void:
	_stop_chase_sound()
	for p in _players.values():
		p.stop()
		p.stream = null
		p.free()
	_players.clear()
	for c in get_children():  # P2-20: one-shots (footsteps) still playing at quit hold the WAV and its playback
		if c is AudioStreamPlayer or c is AudioStreamPlayer3D:
			c.stop()
			c.stream = null
			c.free()
	_cache.clear()


## Streams exist only after the editor import has run (clean checkout); a missing one is a silent layer.
func _stream(id: String, loop: bool = false) -> AudioStream:
	if _cache.has(id):
		return _cache[id]
	var path := "res://assets/audio/%s.wav" % id
	var s: AudioStream = load(path) if ResourceLoader.exists(path) else null
	if s is AudioStreamWAV and loop:
		s = s.duplicate()
		s.loop_mode = AudioStreamWAV.LOOP_FORWARD
		s.loop_begin = 0
		s.loop_end = s.data.size() / (2 * (2 if s.stereo else 1))
	_cache[id] = s
	return s


func _start_layers() -> void:
	for id in _players:
		if _players[id].stream and not _players[id].playing:
			_players[id].play(_rng.randf() * 4.0)  # desync from the other clients' beds, not from each other


func _on_node_added(n: Node) -> void:
	if n.has_signal(&"state_changed") and n.name == &"Creature":
		_hook_creature.call_deferred(n)


func _hook_creature(c: Node) -> void:
	if not c.state_changed.is_connected(set_creature_state):
		c.state_changed.connect(set_creature_state)
		set_creature_state(c.state, c.body, true)


func _on_apply(what: StringName, args: Array) -> void:
	if what == &"lure" and args[1] == "stranger":  # args: lure_id, source, position, slot, tell, ghost
		play_3d(STRANGER_LINES[hash(args[0]) % STRANGER_LINES.size()], args[2])
	elif what == &"trap_changed" and args[2] == &"sprung":  # args: id, kind, state, position (P1-09)
		play_3d(&"sfx_beartrap_snap" if args[1] == &"bear" else &"sfx_pit_fall", args[3])
	elif what == &"emote" and args[1] != &"scream":  # args: peer, emote_id, position; the scream is whistle_emotes'
		play_3d(&"sfx_emote_cloth", args[2])


## The Dawn Report card slides in on every peer. Its log line, not `apply_dawn_report`: the host shows
## its own card without that RPC (dawn_report.gd sends it to the other peers only).
func _on_logged(event: StringName, _data: Dictionary) -> void:
	if event == &"dawn_report_shown":
		play_2d(&"ui_paper_slide")
		for n in get_tree().root.find_children("*", "CanvasLayer", true, false):
			if n is DawnReport:
				_report = n
		set_report_open(true)


## D-074 / Q-072: while the Dawn Report is up, a 1.2 kHz low-pass on Ambience and SFX only (the `Report`
## effects in default_bus_layout.tres); Voice, Creature and UI stay clear. `dawn_report.gd` logs no close
## event, so `_process` watches its `_open` flag (placeholder coupling: a close event would replace it).
func set_report_open(on: bool) -> void:
	for bus in [&"SFX", &"Ambience"]:
		var b := AudioServer.get_bus_index(bus)
		for i in AudioServer.get_bus_effect_count(b):
			if AudioServer.get_bus_effect(b, i).resource_name == "Report":
				AudioServer.set_bus_effect_enabled(b, i, on)
	_report_on = on


## Doc 08 section 4.3. `snap` skips the fade (late join).
func set_creature_state(state: StringName, body: StringName, snap: bool = false) -> void:
	var was := creature_state
	creature_state = state
	creature_body = body
	_dropped_t = 0.0
	if state == &"chase":
		if was != &"chase" and not snap:
			play_2d(&"mus_sting_chase")  # doc 08 section 5.3: once on entry, every peer (Q-048 (2))
			Log.event(&"audio_chase_cue", {"body": String(body)})
		_start_chase_sound()
	else:
		_stop_chase_sound()
	match state:
		&"stalk", &"chase":
			_tell_target.bed = BED_OFF_DB
			_tell_target.wind = WIND_DROP_DB
			_tell_rate.bed = BED_OFF_DB / 0.8
			_tell_rate.wind = WIND_DROP_DB / 2.0
		&"retreat":
			_return_layers(4.0, 6.0)
		_:
			if was in [&"stalk", &"chase"]:
				_return_layers(8.0, 10.0)  # a lost chase: the layers must not stay off in a toneless state
	if snap:
		_tell_db.bed = _tell_target.bed
		_tell_db.wind = _tell_target.wind
	_log_state()


## Signature loop on the creature node (moves with it), plus the local kill-warning heartbeat.
func _start_chase_sound() -> void:
	_stop_chase_sound()
	_chase_t = 0.0
	var c := get_tree().get_first_node_in_group(&"creature") as Node3D
	var sig_id := "cre_%s_sig_chase" % String(creature_body).trim_prefix("body_")  # creature_body is "body_gaunt" etc.
	var s := _stream(sig_id, true)
	Log.event(&"audio_chase_sig", {"id": sig_id, "stream": s != null, "creature": c != null})
	if c and s:
		_sig = SoundEmitter.new()
		_sig.stream = s
		_sig.bus = &"Creature"
		_sig.unit_size = SIG_UNIT
		_sig.max_distance = SIG_MAX
		_sig.volume_db = SIG_DB
		c.add_child(_sig)
		_sig.play()
	var h := _stream("sfx_still_heartbeat_loop", true)
	if CHASE_HEARTBEAT and h and not Game.is_ghost(Game.local_peer()):
		_heart = AudioStreamPlayer.new()
		_heart.stream = h
		_heart.bus = &"SFX"
		_heart.volume_db = HEART_DB[0]
		add_child(_heart)
		_heart.play()


func _stop_chase_sound() -> void:
	for n in [_sig, _heart]:
		if is_instance_valid(n):
			n.stop()
			n.stream = null  # no playback may outlive the tree ("resources still in use at exit")
			n.queue_free()
	_sig = null
	_heart = null


## P3-05 scare build-up (doc 03 section 13): on this peer only, insects cut and the wind drops for
## `seconds`, then the layers return unless the creature's state still holds them down.
func hush(seconds: float) -> void:
	_tell_target.bed = BED_OFF_DB
	_tell_target.wind = maxf(_tell_target.wind, HUSH_WIND_DB)
	_tell_rate.bed = BED_OFF_DB / 0.8
	_tell_rate.wind = HUSH_WIND_DB / 1.0
	Log.event(&"audio_hush", {"seconds": seconds})
	await get_tree().create_timer(seconds).timeout
	if not is_inside_tree():
		return
	if not creature_state in [&"stalk", &"chase"]:
		_return_layers(4.0, 6.0)


func _return_layers(bed_s: float, wind_s: float) -> void:
	_tell_target.bed = 0.0
	_tell_target.wind = 0.0
	_tell_rate.bed = BED_OFF_DB / bed_s
	_tell_rate.wind = WIND_DROP_DB / wind_s


## Doc 08 section 4.1: dusk and night take the night bed; dawn and day the day bed.
func set_phase(phase: StringName, snap: bool = false) -> void:
	_night_target = 1.0 if phase in [&"dusk", &"night", &"harvest_moon"] else 0.0
	if snap:
		_night = _night_target


func _process(delta: float) -> void:
	_barn = move_toward(_barn, 1.0 if _in_barn() else 0.0, delta / BARN_FADE_S)
	if _report_on and (not is_instance_valid(_report) or not _report._open):
		set_report_open(false)
	if is_instance_valid(_heart):
		_chase_t += delta
		var k := clampf(_chase_t / HEART_RAMP_S, 0.0, 1.0)
		_heart.volume_db = lerpf(HEART_DB[0], HEART_DB[1], k)
		_heart.pitch_scale = lerpf(HEART_PITCH[0], HEART_PITCH[1], k)
	_taint_heartbeat()
	_night = move_toward(_night, _night_target, delta / PHASE_FADE_S)
	if creature_state in [&"stalk", &"chase"]:
		_dropped_t += delta
		# Failsafe (doc 08 section 4.3): a lost state message must not leave the farm silent.
		if _dropped_t > (30.0 if creature_state == &"stalk" else 45.0):
			_return_layers(8.0, 10.0)
			_stop_chase_sound()
	for k in _tell_db:
		_tell_db[k] = move_toward(_tell_db[k], _tell_target[k], _tell_rate[k] * delta)
	_apply_gains()
	_footsteps(delta)
	_log_t += delta
	if _log_t >= 5.0 and creature_state != &"lurk":
		_log_state()


## Doc 01 "The Taint": a faint wet heartbeat "in your audio", so only on the Tainted player's own machine.
## Polls the local flag (set by `Net.apply_taint_changed` on the host and the Tainted client, P3-07).
func _taint_heartbeat() -> void:
	var me := Game.local_peer()
	var on := bool(Game.players.get(me, {}).get("tainted", false)) and not Game.is_ghost(me)
	if on and not is_instance_valid(_taint):
		var s := _stream("sfx_taint_heartbeat", true)
		if s == null:
			return
		_taint = AudioStreamPlayer.new()
		_taint.stream = s
		_taint.bus = &"SFX"
		add_child(_taint)
		_taint.play()
		Log.event(&"audio_taint_heartbeat", {"on": true})
	elif not on and is_instance_valid(_taint):
		_taint.stop()
		_taint.stream = null
		_taint.queue_free()
		_taint = null
		Log.event(&"audio_taint_heartbeat", {"on": false})
	if is_instance_valid(_taint):
		_taint.volume_db = TAINT_DB - (TAINT_DUCK_DB if is_instance_valid(_heart) else 0.0)


## The barn bed plays in the lobby and while the recording screen is open (anywhere).
func _in_barn() -> bool:
	if Game.in_lobby:
		return true
	for c in Voice.get_children():
		if c is RecordingScreen:
			return true
	return false


func _apply_gains() -> void:
	var g_night := sin(_night * PI * 0.5)
	for id in _players:
		var cfg: Dictionary = LAYERS[id]
		var db := SILENT_DB
		if id == &"barn":
			db = cfg.night + linear_to_db(_barn) if _barn > 0.001 else SILENT_DB
		elif id == &"wind":
			db = lerpf(cfg.day, cfg.night, _night) - _tell_db.wind
		else:
			var share := g_night
			if share > 0.001:
				db = cfg.night + linear_to_db(share) - _tell_db.bed
		_players[id].volume_db = maxf(db, SILENT_DB)


## Doc 08 section 10.4: for a client's `peer_<id>.jsonl`, "the bed didn't drop" quotes these gains.
func _log_state() -> void:
	_log_t = 0.0
	Log.event(&"audio_state", {"state": String(creature_state), "body": String(creature_body),
			"bed_db": snappedf(_players[&"insect_night"].volume_db, 0.1), "wind_db": snappedf(_players[&"wind"].volume_db, 0.1), "recent": recent.map(func(s): return String(s))})


## One-shot at a world position (doc 08 section 10.1). `opts`: `db` extra trim.
func play_3d(id: StringName, pos: Vector3, opts: Dictionary = {}) -> void:
	var c: Dictionary = CATALOG.get(id, {})
	if c.is_empty() or _emitters >= MAX_EMITTERS:
		return
	var s := _stream(_variant(id, int(c.n)))
	if s == null:
		return
	var p := SoundEmitter.new()
	p.stream = s
	p.bus = c.bus
	p.unit_size = c.unit
	p.max_distance = c.max
	p.volume_db = float(c.db) + float(opts.get("db", 0.0))
	p.pitch_scale = _rng.randf_range(0.95, 1.05) * float(opts.get("pitch", 1.0))
	_emitters += 1
	p.finished.connect(func() -> void:
		_emitters -= 1
		p.queue_free())
	add_child(p)
	p.global_position = pos
	p.play()
	_played(id)


## Non-positional one-shot (own footsteps, UI).
func play_2d(id: StringName, db: float = 0.0, pitch: float = 1.0) -> void:
	var c: Dictionary = CATALOG.get(id, {})
	var s := _stream(_variant(id, int(c.get("n", 0))))
	if s == null:
		return
	var p := AudioStreamPlayer.new()
	p.stream = s
	p.bus = c.get("bus", &"SFX")
	p.volume_db = float(c.get("db", 0.0)) + db
	p.pitch_scale = pitch
	p.finished.connect(p.queue_free)
	add_child(p)
	p.play()
	_played(id)


## File name for one play: a random variant `_NN`, never the one this id played last (P4-26).
func _variant(id: StringName, n: int) -> String:
	if n <= 0:
		return String(id)
	var v := _rng.randi_range(1, n)
	if n > 1 and v == int(_last_variant.get(id, 0)):
		v = v % n + 1
	_last_variant[id] = v
	return "%s_%02d" % [id, v]


## Doc 08 section 10.4: the last 8 ids for `audio_state`, and an `audio_play` line so a log shows each cue's trigger.
func _played(id: StringName) -> void:
	recent.append(id)
	if recent.size() > 8:
		recent.pop_front()
	if not id in QUIET_LOG:
		Log.event(&"audio_play", {"id": String(id)})


# --- Footsteps (doc 08 sections 3.2, 10.2) --------------------------------------------------------
# Derived from replicated positions, one step per stride, so a client hears the same steps the host's
# Noise counts. Crouching is silent (doc 01 "Hiding verbs"). Own steps are non-positional and quieter.

func _footsteps(delta: float) -> void:
	var root := get_tree().current_scene
	var pl := root.get_node_or_null(^"Players") if root else null
	if pl == null or delta <= 0.0:
		return
	for n in pl.get_children():
		if not "peer" in n or n.get(&"peer") == 0:
			continue
		var peer: int = n.peer
		var pos: Vector3 = n.global_position
		var prev: Vector3 = _prev_pos.get(peer, pos)
		_prev_pos[peer] = pos
		var flat := Vector2(pos.x - prev.x, pos.z - prev.z).length()
		if flat > 3.0 or Game.is_ghost(peer) or bool(n.get(&"crouching")):  # a teleport, a ghost or a crouch
			continue
		_stride[peer] = float(_stride.get(peer, 0.0)) + flat
		if _stride[peer] < STRIDE_M:
			continue
		_stride[peer] = 0.0
		# ponytail: speed guess, halfway between walk (3) and sprint (5); the replicated sprint flag is host-only
		var sprint := flat / delta > (Data.speed(&"walk") + Data.speed(&"sprint")) * 0.5
		var id := _step_surface(pos)
		var db := (6.0 if sprint else 0.0) + _rng.randf_range(STEP_DB.x, STEP_DB.y)
		var pitch := _rng.randf_range(STEP_PITCH.x, STEP_PITCH.y)
		if bool(n.get(&"is_local")):
			play_2d(id, db - 8.0, pitch)
		else:
			play_3d(id, pos, {"db": db, "pitch": pitch})


## Doc 08 section 11.2: corn (layer 5 point query), wood inside a building, dirt elsewhere.
func _step_surface(pos: Vector3) -> StringName:
	var q := PhysicsPointQueryParameters3D.new()
	q.position = pos + Vector3.UP
	q.collision_mask = CORN_MASK
	q.collide_with_areas = true
	var w := get_viewport().world_3d
	if w and not w.direct_space_state.intersect_point(q, 1).is_empty():
		return &"sfx_step_corn"
	if _floors_scene != get_tree().current_scene:
		_build_floors()
	for r in _floors:
		if r.has_point(Vector2(pos.x, pos.z)):
			return &"sfx_step_wood"
	return &"sfx_step_dirt"


## Each building is a `doors` marker's parent with wall bodies at its edges; the walls' centres bound the floor.
func _build_floors() -> void:
	_floors_scene = get_tree().current_scene
	_floors.clear()
	for d in get_tree().get_nodes_in_group(&"doors"):
		var b := d.get_parent()
		var r := Rect2()
		var first := true
		for w in b.get_children():
			if w is StaticBody3D:
				var p := Vector2(w.global_position.x, w.global_position.z)
				r = Rect2(p, Vector2.ZERO) if first else r.expand(p)
				first = false
		if r.has_area():
			_floors.append(r)
