extends Node
## Doc 08 section 10: the one place that turns replicated state into sound. Autoload `Soundscape`.
## Runs on every peer, never talks to the network, only listens: `Creature.state_changed` (group
## `creature`, fires on host and clients), `Net.apply_received` lure, `Clock.phase_changed`.
##
## Three ambience layers (doc 08 section 4): wind, insect bed (day and night crossfaded) and frog bed.
## Rule (doc 08 section 4.4): only `set_creature_state()` lowers the `bed` or `wind` layers, through
## `_tell_target`; the phase crossfade is equal-power between two beds, never through silence.
## Every sound is a placeholder generated by `assets/audio/src/<id>.scd` (D-015).

const CATALOG := {  # id -> variants, bus, unit_size, max_distance, volume_db (doc 08 sections 3.2, 11)
	&"sfx_step_dirt": {"n": 2, "bus": &"SFX", "unit": 3.0, "max": 40.0, "db": -8.0},
	&"sfx_step_corn": {"n": 2, "bus": &"SFX", "unit": 3.0, "max": 40.0, "db": -8.0},
	&"sfx_beartrap_snap": {"n": 0, "bus": &"SFX", "unit": 6.0, "max": 110.0, "db": -4.0},
	&"sfx_pit_fall": {"n": 0, "bus": &"SFX", "unit": 6.0, "max": 110.0, "db": -4.0},
	&"sfx_whistle": {"n": 0, "bus": &"SFX", "unit": 20.0, "max": 220.0, "db": -4.0},
	&"vox_stranger_over_here": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_help": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_anyone": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_come": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_lost": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
	&"vox_stranger_hello": {"n": 0, "bus": &"Voice", "unit": 6.0, "max": 80.0, "db": -8.0},
}
const STRANGER_LINES: Array[StringName] = [&"vox_stranger_over_here", &"vox_stranger_help",
		&"vox_stranger_anyone", &"vox_stranger_come", &"vox_stranger_lost", &"vox_stranger_hello"]
## Layer levels in dB: [day, night] (doc 08 section 4.1, placeholder). The insect bed has two files.
const LAYERS := {
	&"wind": {"file": "amb_wind_loop", "day": -26.0, "night": -20.0},
	&"insect_day": {"file": "amb_insect_bed_day", "day": -24.0, "night": -80.0},
	&"insect_night": {"file": "amb_insect_bed_night", "day": -80.0, "night": -22.0},
	&"frog": {"file": "amb_frog_bed", "day": -80.0, "night": -26.0},
}
const WIND_DROP_DB := 18.0  ## doc 08 section 4.3 stalk
const BED_OFF_DB := 60.0
const PHASE_FADE_S := 45.0  ## doc 08 section 4.1 dusk crossfade
const MAX_EMITTERS := 32  ## doc 08 section 2.3 rule 7
const STRIDE_M := 1.6  ## same stride as the host's footstep Noise (players.gd)
const SILENT_DB := -80.0

var creature_state: StringName = &"lurk"
var creature_body: StringName = &""
var recent: Array[StringName] = []  ## last 8 sound ids (doc 08 section 10.4)

var _players: Dictionary = {}  ## layer -> AudioStreamPlayer
var _night := 0.0  ## 0 day bed, 1 night bed; equal-power crossfade
var _night_target := 0.0
var _tell_db := {&"bed": 0.0, &"wind": 0.0}  ## offset below base, set only through _tell_target
var _tell_target := {&"bed": 0.0, &"wind": 0.0}
var _tell_rate := {&"bed": 60.0, &"wind": 9.0}  ## dB per second
var _dropped_t := 0.0
var _log_t := 0.0
var _emitters := 0
var _cache: Dictionary = {}
var _prev_pos: Dictionary = {}
var _stride: Dictionary = {}
var _rng := RandomNumberGenerator.new()


func _ready() -> void:
	_rng.randomize()
	for id in LAYERS:
		var p := AudioStreamPlayer.new()
		p.bus = &"Ambience"
		p.volume_db = SILENT_DB
		p.stream = _stream(String(LAYERS[id].file), true)
		add_child(p)
		_players[id] = p
	set_phase(Clock.phase, true)
	Clock.phase_changed.connect(set_phase)
	Net.apply_received.connect(_on_apply)
	get_tree().node_added.connect(_on_node_added)
	for c in get_tree().get_nodes_in_group(&"creature"):
		_hook_creature(c)
	_apply_gains()
	_start_layers()


## Free players and drop cached streams so no AudioStreamWAV / playback outlives the tree ("resources still in use at exit").
func _exit_tree() -> void:
	for p in _players.values():
		p.stop()
		p.stream = null
		p.free()
	_players.clear()
	_cache.clear()


## Streams exist only after the editor import has run (clean checkout); a missing one is a silent layer.
func _stream(id: String, loop: bool = false) -> AudioStream:
	if _cache.has(id):
		return _cache[id]
	var path := "res://assets/audio/%s.wav" % id
	var s: AudioStream = load(path) if ResourceLoader.exists(path) else null
	if s is AudioStreamWAV and loop:
		s = s.duplicate()
		s.loop_mode = AudioStreamWAV.LOOP_FORWARD
		s.loop_begin = 0
		s.loop_end = s.data.size() / (2 * (2 if s.stereo else 1))
	_cache[id] = s
	return s


func _start_layers() -> void:
	for id in _players:
		if _players[id].stream and not _players[id].playing:
			_players[id].play(_rng.randf() * 4.0)  # desync from the other clients' beds, not from each other


func _on_node_added(n: Node) -> void:
	if n.has_signal(&"state_changed") and n.name == &"Creature":
		_hook_creature.call_deferred(n)


func _hook_creature(c: Node) -> void:
	if not c.state_changed.is_connected(set_creature_state):
		c.state_changed.connect(set_creature_state)
		set_creature_state(c.state, c.body, true)


func _on_apply(what: StringName, args: Array) -> void:
	if what == &"lure" and args[1] == "stranger":  # args: lure_id, source, position, slot, tell, ghost
		play_3d(STRANGER_LINES[hash(args[0]) % STRANGER_LINES.size()], args[2])
	elif what == &"trap_changed" and args[2] == &"sprung":  # args: id, kind, state, position (P1-09)
		play_3d(&"sfx_beartrap_snap" if args[1] == &"bear" else &"sfx_pit_fall", args[3])


## Doc 08 section 4.3. `snap` skips the fade (late join).
func set_creature_state(state: StringName, body: StringName, snap: bool = false) -> void:
	var was := creature_state
	creature_state = state
	creature_body = body
	_dropped_t = 0.0
	match state:
		&"stalk", &"chase":
			_tell_target.bed = BED_OFF_DB
			_tell_target.wind = WIND_DROP_DB
			_tell_rate.bed = BED_OFF_DB / 0.8
			_tell_rate.wind = WIND_DROP_DB / 2.0
		&"retreat":
			_return_layers(4.0, 6.0)
		_:
			if was in [&"stalk", &"chase"]:
				_return_layers(8.0, 10.0)  # a lost chase: the layers must not stay off in a toneless state
	if snap:
		_tell_db.bed = _tell_target.bed
		_tell_db.wind = _tell_target.wind
	_log_state()


func _return_layers(bed_s: float, wind_s: float) -> void:
	_tell_target.bed = 0.0
	_tell_target.wind = 0.0
	_tell_rate.bed = BED_OFF_DB / bed_s
	_tell_rate.wind = WIND_DROP_DB / wind_s


## Doc 08 section 4.1: dusk and night take the night bed; dawn and day the day bed.
func set_phase(phase: StringName, snap: bool = false) -> void:
	_night_target = 1.0 if phase in [&"dusk", &"night", &"harvest_moon"] else 0.0
	if snap:
		_night = _night_target


func _process(delta: float) -> void:
	_night = move_toward(_night, _night_target, delta / PHASE_FADE_S)
	if creature_state in [&"stalk", &"chase"]:
		_dropped_t += delta
		# Failsafe (doc 08 section 4.3): a lost state message must not leave the farm silent.
		if _dropped_t > (30.0 if creature_state == &"stalk" else 45.0):
			_return_layers(8.0, 10.0)
	for k in _tell_db:
		_tell_db[k] = move_toward(_tell_db[k], _tell_target[k], _tell_rate[k] * delta)
	_apply_gains()
	_footsteps(delta)
	_log_t += delta
	if _log_t >= 5.0 and creature_state != &"lurk":
		_log_state()


func _apply_gains() -> void:
	var g_night := sin(_night * PI * 0.5)
	var g_day := cos(_night * PI * 0.5)
	for id in _players:
		var cfg: Dictionary = LAYERS[id]
		var db := SILENT_DB
		if id == &"wind":
			db = lerpf(cfg.day, cfg.night, _night) - _tell_db.wind
		else:
			var day: bool = id == &"insect_day"
			var share := g_day if day else g_night
			if share > 0.001:
				db = (cfg.day if day else cfg.night) + linear_to_db(share) - _tell_db.bed
		_players[id].volume_db = maxf(db, SILENT_DB)


## Doc 08 section 10.4: for a client's `peer_<id>.jsonl`, "the bed didn't drop" quotes these gains.
func _log_state() -> void:
	_log_t = 0.0
	Log.event(&"audio_state", {"state": String(creature_state), "body": String(creature_body),
			"bed_db": snappedf(maxf(_players[&"insect_night"].volume_db, _players[&"insect_day"].volume_db), 0.1), "wind_db": snappedf(_players[&"wind"].volume_db, 0.1),
			"frog_db": snappedf(_players[&"frog"].volume_db, 0.1), "recent": recent.map(func(s): return String(s))})


## One-shot at a world position (doc 08 section 10.1). `opts`: `db` extra trim.
func play_3d(id: StringName, pos: Vector3, opts: Dictionary = {}) -> void:
	var c: Dictionary = CATALOG.get(id, {})
	if c.is_empty() or _emitters >= MAX_EMITTERS:
		return
	var file := String(id) if int(c.n) == 0 else "%s_%02d" % [id, _rng.randi_range(1, int(c.n))]
	var s := _stream(file)
	if s == null:
		return
	var p := SoundEmitter.new()
	p.stream = s
	p.bus = c.bus
	p.unit_size = c.unit
	p.max_distance = c.max
	p.volume_db = float(c.db) + float(opts.get("db", 0.0))
	p.pitch_scale = _rng.randf_range(0.95, 1.05)
	_emitters += 1
	p.finished.connect(func() -> void:
		_emitters -= 1
		p.queue_free())
	add_child(p)
	p.global_position = pos
	p.play()
	recent.append(id)
	if recent.size() > 8:
		recent.pop_front()


## Non-positional one-shot (own footsteps, UI).
func play_2d(id: StringName, db: float = 0.0) -> void:
	var c: Dictionary = CATALOG.get(id, {})
	var file := String(id) if c.is_empty() or int(c.n) == 0 else "%s_%02d" % [id, _rng.randi_range(1, int(c.n))]
	var s := _stream(file)
	if s == null:
		return
	var p := AudioStreamPlayer.new()
	p.stream = s
	p.bus = c.get("bus", &"SFX")
	p.volume_db = float(c.get("db", 0.0)) + db
	p.finished.connect(p.queue_free)
	add_child(p)
	p.play()


# --- Footsteps (doc 08 sections 3.2, 10.2) --------------------------------------------------------
# Derived from replicated positions, one step per stride, so a client hears the same steps the host's
# Noise counts. Crouching is silent (doc 01 "Hiding verbs"). Own steps are non-positional and quieter.

func _footsteps(delta: float) -> void:
	var root := get_tree().current_scene
	var pl := root.get_node_or_null(^"Players") if root else null
	if pl == null or delta <= 0.0:
		return
	for n in pl.get_children():
		if not "peer" in n or n.get(&"peer") == 0:
			continue
		var peer: int = n.peer
		var pos: Vector3 = n.global_position
		var prev: Vector3 = _prev_pos.get(peer, pos)
		_prev_pos[peer] = pos
		var flat := Vector2(pos.x - prev.x, pos.z - prev.z).length()
		if flat > 3.0 or Game.is_ghost(peer) or bool(n.get(&"crouching")):  # a teleport, a ghost or a crouch
			continue
		_stride[peer] = float(_stride.get(peer, 0.0)) + flat
		if _stride[peer] < STRIDE_M:
			continue
		_stride[peer] = 0.0
		var sprint := flat / delta > 5.0  # ponytail: speed guess; replicated sprint flag is host-only
		var id: StringName = &"sfx_step_dirt"
		if bool(n.get(&"is_local")):
			play_2d(id, -8.0 + (6.0 if sprint else 0.0))
		else:
			play_3d(id, pos, {"db": 6.0 if sprint else 0.0})
